### ISSUE TITLE
v0.0 submission

### ISSUE THREAD

**Issue by JoshuaChing** [CS2103JAN2017-T11-B4/main#13]
Update the relevant sections of the relevant markdown documents (i.e. UserGuide.md, DeveloperGuide.md) in your repo. git tag as V0.0.

**Comment by KellyLi** [comment]
@evanyeung Is this done?

**Comment by evanyeung** [comment]
I think we're still waiting on #12 (@Yefenyi)

**Comment by evanyeung** [comment]
Created tag and release for v0.0
