### ISSUE TITLE
Feedback for V0.3

### ISSUE THREAD

**Issue by ZawadulFarhan** [CS2103JAN2017-T11-B4/main#140]
## AboutUs

@Yefenyi, please update your mugshot with a clear shot of your full face.

### 2.2. `add` Command

AND can be ommitted when referring to the DATE and TIME parameters.

### 2.5. `sort` Command

Could elaborate further on what `SORTCRITERIA` means. Also try to make the nomenclature consistent. `TASK_NAME` in the add command format is delimited by a '_' while `SORTCRITERIA` is not.

### 2.6. `edit` Command

The command format should reflect which portions of the command is optional with square brackets. Is the `NEWDESCRIPTION` referring to the same thing as `TASK_NAME`? If so, refer to both of them as either description or name.

### 2.10. `find` Command

Consider whether a case sensitive search will be useful for users. If a user were to key in a task named 'collect package from Andy', would he remember whether he typed in andy or Andy? Also consider whether an AND or OR search is preferred for multiple keyword.

### 4. Command Summary

Deleteall seems to be incorrectly formatted. It also uses a command format that is different than what is discussed in section 2.9. Edit command format suggests you do not need a / after you put the parameter type which is different from what is in section 2.6.

### General

Do note that specifying a save directory through a command is a must have feature. Include these in the user guide even if they have not been implemented yet. The user guide should envision the completed product. Also include any other additional features you have included or plan to implement.

### Content Page

Some of the links do not seem to link to the appropriate section.

### 2.1. Architecture

Does the application connect to the internet? If not, do update the architecture diagram. Sequence diagrams are still referring to addressbook.

### 2.2. UI component

There shouldn't be a `PersonListPanel` and `PersonCard` class in your task management application. I believe the `BrowserPanel` has been removed in your GUI.

### 3.3. Undo/Redo

It is good that you included implementation details of undo/redo but this is not reflected in the structure of the components.

### Appendix B

'Use case ends' and 'Use case resumes from step #' should be put in a new line.

### Appendix C

Point 6 could be put in the form of a proper sentence.

@KellyLi @JoshuaChing @evanyeung @Yefenyi  For your action.

**Comment by evanyeung** [comment]
@KellyLi, are all of these in other issues already? If so, we should be able to just close this one.

**Comment by KellyLi** [comment]
They are. I was thinking to leave it open until all of them have been addressed.
