### ISSUE TITLE
Delete clear command since we do not support it for undo and redo

### ISSUE THREAD

**Issue by KellyLi** [CS2103JAN2017-T11-B4/main#206]
- [x] Delete code
- [x] Update docs

**Comment by JoshuaChing** [comment]
is clear not a part of the core requirements?

**Comment by KellyLi** [comment]
I don't see it in the handbook

Must-have features:

Support for events (i.e., has a start time and end time), deadlines (tasks that have to be done before a specific deadline), and floating tasks (tasks without specific times). Note that these category names are temporary names only. You should figure out what are the best names for these categories. Are these names intuitive to end-users? Should they even care about consciously categorizing tasks?
CRUD (i.e., Create, Read, Update, Delete) support for tasks.
Undo operations (at least for the most recent action)
Some flexibility in the command format, i.e. support a few natural variations of the command format.
Simple search: A simple text search for finding an item if the user remembers some keywords from the item description.
Some way to keep track of which items are done and which are yet to be done.
The ability to specify a specific folder and a file for data storage. With this feature, Jim can choose to store the data file in a local folder controlled by a cloud syncing service (e.g. dropbox), allowing him to access task data from multiple computers.
